[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
  "cd api-orders",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd api-orders && python -c 'import app.main'"]

[start]
cmd = "bash start.sh"

[variables]
PYTHONUNBUFFERED = "1"