[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["cd api-orders && pip install -r requirements.txt"]

[start]
cmd = "cd api-orders && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8003}"